### ISSUE TITLE
Accessing the Merchant Registry frontend page

### ISSUE THREAD

**Issue by robamon** [mojaloop/merchant-registry-svc#97]
What credentials are used to access the Merchant Registry frontend page  running on port 5173? 

![Merchant Registry](https://github.com/mojaloop/merchant-registry-svc/assets/136369652/fe9e77b0-b0e2-4fe1-8ce9-2ea746c89023)

**Comment by robamon** [comment]
@nainglinnkhant can you assist on this. Have tried all the preset credentials and none seems to work.

**Comment by tw-sithumyo** [comment]
Hi @robamon,  after the `docker-compose up --build`,
you should be able to login with one of the credentials described in 
https://github.com/mojaloop/merchant-registry-svc/blob/master/packages/acquirer-backend/src/database/defaultUsers.ts

**Comment by robamon** [comment]
@tw-sithumyo Thank you for responding. I have already done that but still getting login failed error. I have attempted for all the default users and the result is the same:
![login failed](https://github.com/mojaloop/merchant-registry-svc/assets/136369652/f45ef387-96b3-4a50-82de-ffc1d6d46225)

**Comment by robamon** [comment]
@tw-sithumyo @nainglinnkhant 
I have cloned a new repo and installed on a new OS instance but I still keep getting the same error as per the screenshot. What is it that I'm doing wrong?
![error_merchant](https://github.com/mojaloop/merchant-registry-svc/assets/136369652/fe222a1c-3d19-4f02-ba8d-92a1c9fe5740)

**Comment by robamon** [comment]
unresolved but closed
